### ISSUE TITLE
Wiretap makes it impossible to start the server

### ISSUE THREAD

**Issue by rtgxjzgsryksryydtyrkry** [henkelmax/wiretap#3]
I restarted my server, It stopped after reading chunk data.

**Steps to reproduce the issue**
1. IDK restart server?
**Expected behavior**
Working server

[2023-10-03-5.log](https://github.com/henkelmax/wiretap/files/12789411/2023-10-03-5.log)
[crash-2023-10-03_09.37.10-server.txt](https://github.com/henkelmax/wiretap/files/12789383/crash-2023-10-03_09.37.10-server.txt)

**Versions**
- 1.20.1
- 0.14.21
[crash-2023-10-03_09.37.10-server.txt](https://github.com/henkelmax/wiretap/files/12789383/crash-2023-10-03_09.37.10-server.txt)
-1.0.3
- Simple Voice Chat 1.20.1-2.4.20

A lot

**Comment by henkelmax** [comment]
Did you try to mess with the NBT data of the heads?

**Comment by rtgxjzgsryksryydtyrkry** [comment]
IDK, mb one of players did something, but they don't have op

**Comment by henkelmax** [comment]
Can you check if this happens on a fresh world?

**Comment by rtgxjzgsryksryydtyrkry** [comment]
When I created a new world everything was ok. One of the players said: "I found mic on my base, broke, placed again and saved in ender chest"

**Comment by henkelmax** [comment]
If you can provide me with steps to reproduce this issue, I can fix it

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Sorry, no idea...
